// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "aws-serverless-jrtest",
    "version": "1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "hello",
        "description": "",
        "operationId": "hello.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planeta": {
      "post": {
        "summary": "crearPlaneta",
        "description": "",
        "operationId": "crearPlaneta.post./planeta",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "201": {
            "description": "Planeta creado satisfactoriamente",
            "schema": {
              "$ref": "#/definitions/PostPlanetBody"
            }
          }
        }
      }
    },
    "/planetas": {
      "get": {
        "summary": "listarPlanetas",
        "description": "",
        "operationId": "listarPlanetas.get./planetas",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Peticion exitosa",
            "schema": {
              "$ref": "#/definitions/Planets"
            }
          }
        }
      }
    },
    "/planetas/{id}": {
      "get": {
        "summary": "listarPlaneta",
        "description": "",
        "operationId": "listarPlaneta.get./planetas/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Peticion exitosa"
          }
        }
      },
      "delete": {
        "summary": "eliminarPlaneta",
        "description": "",
        "operationId": "eliminarPlaneta.delete./planetas/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Planeta destruido"
          }
        }
      }
    }
  },
  "definitions": {
    "Planets": {
      "properties": {
        "diametro": {
          "title": "Planets.diametro",
          "enum": [
            "10465"
          ],
          "type": "string"
        },
        "nombre": {
          "title": "Planets.nombre",
          "type": "string"
        },
        "residentes": {
          "items": {
            "$ref": "#/definitions/Residents",
            "title": "Planets.residentes.[]"
          },
          "title": "Planets.residentes",
          "type": "array"
        },
        "periodo_orbita": {
          "title": "Planets.periodo_orbita",
          "type": "string"
        },
        "lider": {
          "title": "Planets.lider",
          "type": "string"
        },
        "url": {
          "title": "Planets.url",
          "type": "string"
        },
        "poblacion": {
          "title": "Planets.poblacion",
          "type": "string"
        },
        "peliculas": {
          "items": {
            "$ref": "#/definitions/Films",
            "title": "Planets.peliculas.[]"
          },
          "title": "Planets.peliculas",
          "type": "array"
        },
        "superficie_agua": {
          "title": "Planets.superficie_agua",
          "type": "string"
        },
        "editado": {
          "title": "Planets.editado",
          "type": "string"
        },
        "periodo_rotacion": {
          "title": "Planets.periodo_rotacion",
          "type": "string"
        },
        "gravedad": {
          "title": "Planets.gravedad",
          "type": "string"
        },
        "creado": {
          "title": "Planets.creado",
          "type": "string"
        },
        "id": {
          "title": "Planets.id",
          "type": "string"
        },
        "terreno": {
          "title": "Planets.terreno",
          "type": "string"
        }
      },
      "required": [
        "diametro",
        "nombre",
        "residentes",
        "periodo_orbita",
        "lider",
        "url",
        "poblacion",
        "peliculas",
        "superficie_agua",
        "editado",
        "periodo_rotacion",
        "gravedad",
        "creado",
        "id",
        "terreno"
      ],
      "additionalProperties": false,
      "title": "Planets",
      "type": "object"
    },
    "Residents": {
      "title": "Residents"
    },
    "Films": {
      "title": "Films"
    },
    "PostPlanetBody": {
      "properties": {
        "nombre": {
          "title": "PostPlanetBody.nombre",
          "type": "string"
        },
        "lider": {
          "title": "PostPlanetBody.lider",
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "lider"
      ],
      "additionalProperties": false,
      "title": "PostPlanetBody",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};